### DISCUSSION TITLE
Can't get custom style to render

### DISCUSSION THREAD

**Discussion by yanb3n** [wangchucheng/hugo-eureka#198] [Q&A]
Hi there, I can't tell if I'm just a big klutz or what but I can't seem to get custom styles to work?! I've created my own custom `data/styles/mystyle.yaml` and have made a config according to the [default style](https://github.com/wangchucheng/hugo-eureka/blob/master/data/styles/default.yaml)

`params.yml` config:
```yaml
# Colors and fonts. Default style is data/styles/default.yaml/
style: mystyle
```
`mystyle.yaml`  Config
```yaml
# Normal(400), semibold(600), bold(700) font weight needed.
fonts: 
  - name: Roboto
    googleFonts: Roboto:wght@400;600;700 # only changing this for testing

colors:
  light:
    theme: "#38b2ac"
    primaryBackground: rgba(242, 242, 247, 1)
    secondaryBackground: rgba(255, 255, 255, 1)
    tertiaryBackground: rgba(242, 242, 247, 1)
    primaryText: rgba(0, 0, 0, 0.85)
    secondaryText: rgba(0, 0, 0, 0.7)
    tertiaryText: rgba(0, 0, 0, 0.55)
  dark:
    theme: "#38b2ac"
    primaryBackground: rgba(0, 0, 0, 1)
    secondaryBackground: rgba(28, 28, 30, 1)
    tertiaryBackground: rgba(44, 44, 46, 1)
    primaryText: rgba(0, 255, 255, 0.85) # Random colors to make changes obvious
    secondaryText: rgba(0, 255, 255, 0.7)
    tertiaryText: rgba(0, 255, 255, 0.55)
```

I can even see the generated files containing
```html
<link rel="preload"
  href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;600;700&amp;display=swap"
  as="style" onload="this.onload=null;this.rel='stylesheet'">
```

But the site loads using the default font, `Lora`. Is there something that I'm missing here? I'm installed using hugo modules on eureka@v0.9.2, with hugo@v99.1, should I just fall back to editing the submodule for custom formatting?

Apologies in advance, I'm hot garbage at hugo/frontend, thanks for all the help!
