### ISSUE TITLE
docs的目录和toc字体过大，导致显示换行

### ISSUE THREAD

**Issue by georgehao** [wangchucheng/hugo-eureka#110]
![image](https://user-images.githubusercontent.com/6947653/120055476-f1c0ac80-c068-11eb-967a-3d2bf19be6aa.png)

圈出来的地方字体过大，整体美感不太好，有改进方案吗

**Comment by georgehao** [comment]
![image](https://user-images.githubusercontent.com/6947653/120055547-76132f80-c069-11eb-84c0-034ae8ca1126.png)
可以参考下 hugo book

**Comment by georgehao** [comment]
![image](https://user-images.githubusercontent.com/6947653/120055682-3ac53080-c06a-11eb-8fa9-38161da3184f.png)

TOC 与内容之间的间隔太小，有点连在一起的感觉，可以适当增大距离

**Comment by wangchucheng** [comment]
我查看了你之前提到的hugo book，在我看来字体大小是类似的。换行的原因应该是由于宽度问题。目前为保持整体的一致性，宽度进行了限制。将宽度变宽在当前的考虑范围内，但由于这是一个影响较大的样式变化，因此还没有决定。欢迎听到更多的建议！

祝好！

**Comment by georgehao** [comment]
嗯，希望能够调整一下，目前的呈现效果并不是太好。如果宽度的布局不好改变，希望有些增强的功能：
1. 字体大小能够调整
2. 将TOC与内容距离再大一点

**Comment by pluveto** [comment]
```css

    #TableOfContents>ul {
        padding-left: 0;
    }

    .sticky-toc ul {
        font-size: 1rem;
        line-height: 1.5rem;
        list-style-type: none;
        padding-left: 1rem;
    }
```
