### ISSUE TITLE
评论功能添加后新增评论 403

### ISSUE THREAD

**Issue by wen11497110** [wangchucheng/hugo-eureka#112]
博主你好，我新搭建的 hugo 使用了你的这款主题，我按照你的教程添加了 utterances 评论，下面是我的配置
```yaml
comment:
  # Options: disqus, commento, valine and utterances.
  handler: utterances

  # disqus:
  #   shortname:

  utterances:
    # Browse https://utteranc.es/ to see the options available.
    # If you want the color scheme of utterances to follow eureka's, you can set `theme: eureka`.
    repo: "wen11497110/wen11497110.github.io"
    issue-term: "title"
    theme: github-light
```
评论框可以正常显示，但是控制台有报错
```
utterances.3c7bd773.js:1 GET https://api.github.com/repos/wen11497110/wen11497110.github.io/contents/utterances.json?ref=master 404
```
添加评论后，控制台显示 403
```
POST https://api.utteranc.es/repos/wen11497110/wen11497110.github.io/issues 403
```
我发现你的博客评论也有这种问题
