### ISSUE TITLE
Utterances not working - maybe param?

### ISSUE THREAD

**Issue by tknx** [wangchucheng/hugo-eureka#151]
**Describe the bug**

I enabled utterances following the guidelines on the Eureka page. However on my site, the utterance config arguments are not appearing in the HTML code

**To Reproduce**

Does this issue reproduce with the latest release? Yes

My /config/_default/params.yaml file

```
comment:
  # Options: disqus, commento, valine and utterances.
  handler: utterances

  # disqus:
  #   shortname:

  utterances:
  #   # Browse https://utteranc.es/ to see the options available.
  #   # If you want the color scheme of utterances to follow eureka's, you can set `theme: eureka`.
  repo: tknx/thethousandkingdoms
  issue-term: title
  theme: eureka
```

On blog entry where enableComment: true is added to front matter, the HTML of the page only shows the following

```
<script id=utterances src=https://utteranc.es/client.js crossorigin=anonymous async></script>
  | <script>storageColorScheme=="Light"?document.getElementById('utterances').setAttribute('theme','github-light'):storageColorScheme=="Dark"&&document.getElementById('utterances').setAttribute('theme','github-dark')</script>
```

**Expected behavior**

The params set in param.yaml are shown in the output - and also the comments work on the website

**Environment**

 - Hugo Version: latest
 - Eureka Version: latest
