### ISSUE TITLE
按照文档配置后仍然无法渲染代码高亮与数学公式

### ISSUE THREAD

**Issue by Deruck** [wangchucheng/hugo-eureka#163]
如题

相关配置如下

```
highlight:
  handler: highlightjs

  highlightjs:
    # highlight.js doesn't bundle every language. So please specify additional languages you want here.
    # See https://github.com/highlightjs/cdn-release/tree/master/build/languages for available languages.
    languages:
      - dart
      - cpp
      - python
    # See https://github.com/highlightjs/cdn-release/tree/master/build/styles for available styles.
    style: vs2015

math:
  handler: katex

  # katex:
  #   # Browse https://katex.org/docs/options.html to see the options available.
  #   # KaTeX's Auto-render ignores `displayMode` property of the options, so this property will not work.
  #   # You can list the key and value you want as below.
  #   # Because Hugo's config params are case-insensitive, you need to add `-` or `_` before the uppercase letters.
  #   # For example, `throwOnError` should be written as `throw-On-Error` or other acceptable formats.
  #   leqno:

```

实在不知道是哪里出了问题。。求助，谢谢！
