### ISSUE TITLE
Error: module "wangchucheng.com/hugo-eureka" not found

### ISSUE THREAD

**Issue by Fatalerr** [wangchucheng/hugo-eureka#206]
**Describe the bug**

按文档安装好eureka 0.9.3版本后，运行`hugo serve` 失败，提示以下信息：

```
Error: module "wangchucheng.com/hugo-eureka" not found; either add it as a Hugo Module or store it in "c:\\playground\\hugodemo\\themes".: module does not exist
```

**To Reproduce**

Does this issue reproduce with the latest release? **YES**

1. 按文档新建一个site
  ```   
   hugo new site <hugodemo> 
  ```

2. 按照hugo-eureka的文档以submodule的形式添加hugo-euraka

```
  git submodule add https://github.com/wangchucheng/hugo-eureka.git themes/eureka   
```

3. 按照hugo-eureka的文档将theme/eureka/exampleSite下的config和contents文件拷贝到hugodemo的根目录下
4. 在项目的根目录下运行`hugo serve`, 即出现以上错误。 

**Environment**

 - Hugo Version: [hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended windows/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio]
 - Eureka Version: [v0.9.3]

**Additional context**

- 我在做测试时，只将exampleSite下的config和contents目录拷贝到项目根目录下，只修改config/_default/config.yaml文件的title内容，其他未变。

- config/_default/config.yaml的内容：
```
baseURL: /
title: MyDemo

# Uncomment when not installing with Hugo Modules
# theme: eureka
# Comment when not installing with Hugo Modules
theme: wangchucheng.com/hugo-eureka
# If you cannot access the Github mirror, you can also use the Gitee mirror: gitee.com/wangchucheng/hugo-eureka

paginate: 3
copyright: >
  &copy; 2021 <a href="https://www.wangchucheng.com/">WANG Chucheng</a> and <a
  href="https://www.ruiqima.com/">MA Ruiqi</a>
enableEmoji: true
enableGitInfo: false
summaryLength: 75

defaultContentLanguage: en
hasCJKLanguage: false # Set `true` for Chinese/Japanese/Korean.
defaultContentLanguageInSubdir: false

# Uncomment for google analytics
# googleAnalytics: UA-123-45

markup:
  # Do not modify markup.highlight
  highlight:
    codeFences: false
    noClasses: false
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: categories
  tag: tags
  series: series
  author: authors

build:
  useResourceCacheWhen: always
```
