### ISSUE TITLE
Support additional icon e.g. academicons

### ISSUE THREAD

**Issue by chenhao-ye** [wangchucheng/hugo-eureka#213]
**Is your feature request related to a problem? Please describe.**

I would like to use a Google Scholar icon, which is not available on fa. [acadenicons](http://jpswalsh.github.io/academicons/) has provided such icons but I fail to use them. The code below does not show the icon.

```
# about.md
social:
  - icon: google-scholar
    iconPack: ai
    url: https://scholar.google.com/citations?user=XXXXXX
```

**Describe the solution you'd like**

I wonder if there is any existing solution to use `acadenicons`? If there is, that would be great! Otherwise, is it possible to support customized icons features?
