### ISSUE TITLE
找不到指定的Font Awesome图标

### ISSUE THREAD

**Issue by 0xlilim** [wangchucheng/hugo-eureka#216]
首先感谢作者制作如此优秀精良的主题，方便我们搭建自己的博客和乐园。
我现在遇到了一个奇怪的问题，在 homepage 下的 about.md 中的社交媒体部分添加 RSS 订阅图标 时失败了。
我按照 [文档](https://www.wangchucheng.com/zh/docs/hugo-eureka/content-management/#%E4%BD%9C%E8%80%85%E9%A1%B5%E5%8F%82%E6%95%B0) 中提到的修改iconPack和icon内容分别为: fas 和 rss 后，依旧无法显示图标。配置如下：

```
social:
  - icon: envelope
    iconPack: fas
    url: mailto:0xlilim@proton.me
  - icon: twitter
    iconPack: fab
    url: https://twitter.com/0xlilim
  - icon: github
    iconPack: fab
    url: https://github.com/0xlilim
  - icon: rss
    iconPack: fas
    url: https://www.wangchucheng.com/zh/index.xml

```

一开始我以为没有包含到 rss 的图标，但是我进入到  `cd /var/folders/zs/gdxt3dpx46l91h67f2tztbbh0000gn/T/hugo_cache/modules/filecache/modules/pkg/mod/wangchuche
ng.com/hugo-eureka@v0.9.3/_vendor/github.com/FortAwesome/Font-Awesome/js-packages/@fortawesome/free-solid-svg-
icons/` 目录下却发现了它们的存在，查看他们的js内容也是正确的图标:

391 Oct 29 23:20 faRss.d.ts
1239 Oct 29 23:20 faRss.js
397 Oct 29 23:20 faRssSquare.d.ts
]1317 Oct 29 23:20 faRssSquare.js

我尝试过清除浏览器，更换浏览器，重新生成静态文件。可是 RSS 的图标依旧找不到（问号与叹号交替闪烁）

目前版本，使用Hugo Modules方式部署：
- go  1.19.2
- hugo v0.104.3+extended darwin/amd64 BuildDate=unknown
- hugo-eureka@v0.9.3

所以目前这个情况我该如何继续排查问题？能否请您提供一些帮助？十分感谢！
